### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by gun112** [ArbitrumFoundation/docs#183]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

Request: I heard some strange news. When I went to Korea, I participated in this project recommended by my friend and recently I was quite interested in it. But the problem was that my friend was hacked and sent money to my account while staying at home, and I got a call that it was a problem. Maybe that's why you didn't get your assignment?

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to content. Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
