### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by wac2018** [ArbitrumFoundation/docs#185]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

0x3De1c24cCA9a989D128CB7e258199d3394dd65f8

I made the arbitrum nova bridge, made 2 deposits in the arbitrum network, and made 4 transfers 135 days ago. As for this month and February, I made hundreds of transactions.

And I didn't get anything from the airdrop

<img width="940" alt="ARBITROUM NOVA" src="https://user-images.githubusercontent.com/56840437/225655823-3f4d79cd-0deb-447a-9143-d736c09f297e.PNG">

<img width="929" alt="ARBITROUM1" src="https://user-images.githubusercontent.com/56840437/225655863-9718f05d-a731-4c8e-b9fd-3ff4af8fb397.PNG">

<img width="931" alt="ARBITROUM2" src="https://user-images.githubusercontent.com/56840437/225655875-6265017f-c007-4d55-b55b-90995c6a7724.PNG">

<img width="919" alt="ARBITROUM3" src="https://user-images.githubusercontent.com/56840437/225656089-705da724-a80a-44b3-8e8a-208276473991.PNG">

<img width="915" alt="ARBITROUM4" src="https://user-images.githubusercontent.com/56840437/225656149-500192a8-7e2f-419a-9672-0bdb2f858e0c.PNG">

<img width="922" alt="ARBITROUM5" src="https://user-images.githubusercontent.com/56840437/225656173-746aa5b5-a46e-40e0-ab70-bbd5ec9dd707.PNG">

**Comment by wac2018** [comment]
<img width="951" alt="ARBITROUM6" src="https://user-images.githubusercontent.com/56840437/225731971-7192ce7f-f706-420a-a5cc-6ead794874e8.PNG">

**Comment by wac2018** [comment]
<img width="936" alt="ARBITROUM VERFI AIRDROUP" src="https://user-images.githubusercontent.com/56840437/225777801-f172c17f-8180-4ace-a7f4-8cac6c8b2004.PNG">

**Comment by wac2018** [comment]
I checked the jump blacklist, with my address not there

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙

**Comment by wac2018** [comment]
My discord issue is not resolved

**Comment by wac2018** [comment]
Just ignore
