### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by frobenius7** [ArbitrumFoundation/docs#187]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

Request: Something wrong with airdrop amount calculation on https://arbitrum.foundation/ website - differs from doc

see example attached - according doc and checklist to the right i've got 12 points - but calculator shows 5250 points instead of 12000 (as described in doc)
![image](https://user-images.githubusercontent.com/7878433/225668305-ccca2281-24c3-40e0-aebc-78676405b394.png)

**Comment by frobenius7** [comment]
> Hi @frobenius7 can you share your wallet address either here or on [Discord](https://discord.gg/arbitrum) (with a link back to this issue)?

0x685c99E8780e5a7f158617cC2E9acc0e45a66120

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
