### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by Cryptomoon7** [ArbitrumFoundation/docs#194]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

Request: Hello thank you for this Airdrop but I think there is an error because indeed I made more than 250k of transaction, I am a regular user since 2022, you can activate with my address, it seems to me that all my transactions n weren't counted because friends did much less than me but got more, see this screen

My adress : 0x8c0DA62b2F992eC731cE92Fc30B1B5227D8C14a7

Thank you for understanding :pray: :blue_heart:  

![2023-03-16 17_21_05-Traduction](https://user-images.githubusercontent.com/116664128/225685758-d8a524db-65c7-44d7-8253-cbb8c7ed9557.png)

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
