### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by ankaragucueth** [ArbitrumFoundation/docs#197]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

![Ekran görüntüsü 2023-03-16 193110](https://user-images.githubusercontent.com/26296385/225691566-9f8cd127-ee3b-43f1-9899-092938bf47bb.jpg)

Request: (how can we help?)

I have 13 points. transactions are not within 24 hours. I have more than 0.005 eth assets. Don't I need to buy 10200 tokens?
wallet address: 0x22E898e8dc12999494Fcf4CafeA071216c8f8b36
Is your rating wrong?

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
