### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by aloshvalosh** [ArbitrumFoundation/docs#199]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

Request: (how can we help?)

I have made nearly 100 transactions in the past 600 days. However, I have not met the eligibility criteria. After verifying my wallet, I found that it is not enlisted in the Hop protocol or included in the Nansen blacklist.

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
