### ISSUE TITLE
Docs update request: /concepts/sybil-account

### ISSUE THREAD

**Issue by maryam8650** [ArbitrumFoundation/docs#201]
Source: https://docs.arbitrum.foundation/concepts/sybil-account

Request: (how can we help?)

Hi, I checked docs and I should be eligible by at least 8points but site says Im not eligible

by the way I checked my wallet is not in the hop blacklist

I think there is an issue with the site or wallet chekers

my wallet address is 0xfD5BC91F691EC6AAfa609816F8da189C8BD18a00

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
