### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by chinloong0** [ArbitrumFoundation/docs#218]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

Request: (how can we help?)

my address 0x06Ef623E6C10e397A0F2dFfa8c982125328e398c started using arbitrum 397 days ago with 78 transactions and interacted with multiple smart contracts but showing not eligible on checker, and i checked hop blacklist the address is not on there. please help!

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
