### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by VladGera777** [ArbitrumFoundation/docs#220]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

Request: I have problem with my account a don't have airdrop. I have 1 account, but don't have drop. And I have question, why yo don't make KYC, if you wanted to weed out bots. Thanks

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
