### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by ryoaza** [ArbitrumFoundation/docs#225]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

Request: I think you don't consider early adopters, when fuel costs are expensive, at least you consider transactions before 2022, because after 2022 many airdrop hunters are competing to get airdrops, I don't blame your rules but you should pay attention to early adopters,
Thank You

**Comment by DZGoldman** [comment]
Hi @ryoaza — we did our best to make the distribution as fair as possible. Appreciate the feedback, but at this point, the criteria are already fixed.
