### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution - rhino.fi bridge user eligibility

### ISSUE THREAD

**Issue by plutoegg** [ArbitrumFoundation/docs#227]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

**Request:**

Dear Arbitrum Foundation, 

I am reaching out on behalf of the [rhino.fi DeFi project](https://rhino.fi). rhino.fi launched both a cross-chain bridge and cross-chain swap to Arbitrum in 2022, with over 7000 unique bridge transactions made to-date. 

We would like to check to make sure that users that have interacted with the rhino.fi smart contracts on Arbitrum One are counted correctly towards the ARB airdrop, and that the methodology does not incorrectly identify any address that has interacted with the rhino smart contracts as a sybil address.

If possible, can you please enable addresses that have interacted with the following two contracts can be eligible for the ARB criteria ‘Bridging to Arbitrum’ and make sure they are not accidentally counted towards sybil/farming (due to transactions originating from the same address)?

Rhino.fi bridge contract address: 
https://arbiscan.io/address/0x10417734001162ea139e8b044dfe28dbb8b28ad0

Rhino.fi cross-chain swap contract: 
https://arbiscan.io/address/0xca8e436347a46502e353cc36b58fe3bb9214d7fd

We would very much appreciate any assistance that you can give, including clarification as to whether addresses interacting with these addresses may have been blacklisted, since several of our long-term users already alerted us that they do not appear to be eligible.

Kind Regards,

Will
Co-founder rhino.fi

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
