### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution (According to points subtractions)

### ISSUE THREAD

**Issue by osinniy** [ArbitrumFoundation/docs#235]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

In discord [support said](https://discord.com/channels/585084330037084172/585085215605653504/1086407440330936451):
_If a wallet had less than .005 ETH at the moment of the snapshot, one point is subtracted_

but in docs we have one more condition:
_If an airdrop recipient's wallet balance is less than .005 ETH, **and if the wallet hasn't interacted with more than one smart contract, one point is subtracted.**_

If support was right we should remove second criteria from documentation.

**Comment by DZGoldman** [comment]
the content in the docs is valid, thanks
