### ISSUE TITLE
Incorrect point totalling

### ISSUE THREAD

**Issue by bmickish** [ArbitrumFoundation/docs#237]
Hey guys, just finished perusing the reward distribution, and (transactions as far back as July 2022 [though not the requisite 3 minimum to qualify for point doubling]). And according to the screener I've got 9 total points (though 2 from arbitrum nova so I supposed 7+ would be closer to the mark. That said, it only shows 1850 for coins expected, while your literature has it closer to the 7k mark.

![Screenshot_20230318_011333_MetaMask](https://user-images.githubusercontent.com/83976968/226089721-141e5ee2-6044-45ed-a0eb-43c67db21fed.jpg)

I know you guys are stupid busy, so not expecting an answer soon, but I'd appreciate one when you can.

Thanks

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙

**Comment by bmickish** [comment]
Apologies, but thanks for the clarification.

Cheers!
