### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by derpiyero** [ArbitrumFoundation/docs#244]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

Request: (how can we help?)
0xCB5252EA26e624AfBE2DAE7187cBF0447bf19293
![Screenshot_2023-03-19-11-08-20-733_com android chrome](https://user-images.githubusercontent.com/41587000/226162385-72171c05-c2cc-4ab7-8e85-f4f8879ac26e.jpg)

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
