### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by karldecba** [ArbitrumFoundation/docs#255]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

Request: (how can we help?)

Hello good morning. I would like to request an update, since I completed 10 tasks to be eligible for the airdrop, also I am currently still voting and using various protocols of the arbitrum network. Thank you very much and congratulations for this great network that you have put together!

My wallet 0x834744508F8DB61403136b7BcFB07B17D4fe7741

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
