### ISSUE TITLE
Docs update request: /concepts/public-preview-content

### ISSUE THREAD

**Issue by nahim01** [ArbitrumFoundation/docs#259]
Source: https://docs.arbitrum.foundation/concepts/public-preview-content

Request: 0xB5CCBFeA11D97eE6747Ca6fbf4ABeE05f8d1C163

i didn't get arb😭😭

**Comment by nahim01** [comment]
Help post

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
