### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by daniy310** [ArbitrumFoundation/docs#265]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

Request: "The minimum airdrop entitlement is **625** tokens.", but in the table above the minimum is shown at **1250** tokens.
![image](https://user-images.githubusercontent.com/68704220/226832605-1338da77-4e0f-4514-afa3-e52bebaf917f.png)
![image](https://user-images.githubusercontent.com/68704220/226832648-1c9f5c5f-7c77-4951-9430-6f532c663a72.png)

**Comment by DZGoldman** [comment]
The absolute minimum is for pre-nitro points, so half of the mimimum in the table, as explained here:

> Points scored before Arbitrum Nitro were worth twice as much as points scored after -- as a result any points scored after Nitro resulted in half as much of an allocation per point shown in the table above. If an address only became fully eligible (minimum of three points) post-nitro, all points scored counted as post-nitro points.
