### ISSUE TITLE
Docs update request: /how-tos/apply-become-delegate

### ISSUE THREAD

**Issue by Lyssa1** [ArbitrumFoundation/docs#272]
Source: https://docs.arbitrum.foundation/how-tos/apply-become-delegate

Request: (how can we help?)

**Comment by Lyssa1** [comment]
Hello, how do I know if I'm eligible for the airdrop?

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
