### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by mohsen0857** [ArbitrumFoundation/docs#276]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

Request: (how can we help?)
Hello, I have been following you on Twitter, Telegram, and Discord for about a year. I don't know much English, but I have always followed you with Twitter translation.
But now all those who have joined this airdrop for a day or two have won your currency.
It is unfair that I, who have been with you and by your side for so long, should not win any currency.
Please put my wallet in the company's airdrop.
If possible put in airdrop I really needed this money.
I don't want free help, but I didn't expect that I won't win
0x9FFBfae7293A609d3B4B5980A216825D7b3d1a36

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
