### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by Alexgreeneyes82** [ArbitrumFoundation/docs#291]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
 Hello why I’m not elegible for airdrop?
![9502CE38-28B4-4A94-A99D-F4FC0B26BC08](https://user-images.githubusercontent.com/117213015/227374527-0b577576-786b-4e92-b982-aec17555fc13.png)
![AD9751E4-BF5B-4AB7-AF7C-0BC2326BE229](https://user-images.githubusercontent.com/117213015/227374536-5a893a78-80ac-4f4b-8275-f5038629458f.jpeg)
![EF596BDE-7A47-4C62-8A5D-2A600CCD2DD4](https://user-images.githubusercontent.com/117213015/227374544-badc441c-b62d-429e-9adf-4065dc22e8b6.png)

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
