### ISSUE TITLE
Docs update request: /new-arb-chains

### ISSUE THREAD

**Issue by DirtyBoots** [ArbitrumFoundation/docs#295]
Source: https://docs.arbitrum.foundation/new-arb-chains

Request: (how can we help?)

You have a grammatical error in the text below, which you can see in bold and italicized.

Why multiple chains?
Some may ask why the Ethereum ecosystem needs multiple chains at all; wouldn't it be easier to move all activity onto one big rollup chain, like Arbitrum One?

Despite certain conveniences of concentrating all activity onto a single chain, a multi-chain **_ecosystem not is just desirable_**, but necessary for Ethereum's future.

Psst, this issue will be closed with a templated response if it isn't a documentation update request.

**Comment by symbolpunk** [comment]
Thanks @DirtyBoots! #300 addresses this 🙏
