### ISSUE TITLE
DAO allocations from airdrop // where and how?

### ISSUE THREAD

**Issue by ccarfi** [ArbitrumFoundation/docs#302]
cc: @pearring @symbolpunk @DZGoldman 

In the docs here:
https://docs.arbitrum.foundation/airdrop-eligibility-distribution

and in the linked spreadsheet here:
https://docs.google.com/spreadsheets/d/e/2PACX-1vSSAzkIIJqw4WGKCF9gXFUkQojTt6weQTExZYmp3YRIR2TUjir9N8nh8xg7gQ2wuPA8mJKL2neL--to/pubhtml#

...there are a number of DAOs listed in the distribution list. 

Will the airdrop be done to DAO treasury wallets? (If so, how are those wallets mapped to their corresponding DAOs?)

Or do the DAOs need to claim? If so, how does the DAO know which wallet address to claim from?

Was going to ask this in the Discord, but it's a sh*tshow over there right now. :)

**Comment by DZGoldman** [comment]
The target address's for the DAO airdrops were handled case-by-case
