### ISSUE TITLE
Docs update hello, I got a drop and lost it, it's very disappointing, I gave the team more than a year, I still believe and will be a participant, but it's very insulting...: /dao-glossary

### ISSUE THREAD

**Issue by awiseman1** [ArbitrumFoundation/docs#304]
Source: hello, I got a drop and lost it, it's very disappointing, I gave the team more than a year, I still believe and will be a participant, but it's very insulting...
![Screenshot_2023-03-24-01-45-15-361_com android chrome](https://user-images.githubusercontent.com/122393558/227667566-5a322bbe-f503-49fb-b0ee-51f7b79439d6.jpg)

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
