### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by PunkBuster23** [ArbitrumFoundation/docs#337]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution

Request: (how can we help?)--I HAVE DONE TRANSACTIONS THESE PAST MONTHS SIR/MA'AM. AND I WAS JUST WONDERING WHY IM NOT ELIGIBLE FOR THE AIRDROP? THANK YOU SO MUCH FOR YOUR TIME 💯 
<img width="960" alt="transactions 2" src="https://user-images.githubusercontent.com/129413175/228885696-ba50177d-6955-4a36-8d29-b28f41d5c279.png">
<img width="960" alt="transactions 3" src="https://user-images.githubusercontent.com/129413175/228885707-01ec4575-4fbd-437d-819d-ae92f210aec5.png">

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
<img width="960" alt="transactions 1" src="https://user-images.githubusercontent.com/129413175/228885647-8caea878-2fd6-4e57-98f1-be2952f55aef.png">

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
