### ISSUE TITLE
Docs update request: /new-arb-chains

### ISSUE THREAD

**Issue by elinaGittHuB** [ArbitrumFoundation/docs#349]
Source: https://docs.arbitrum.foundation/new-arb-chains

Request: (how can we help?)creat a crypto Currency app Wallet with a #send address, a #contract address and a secret key and give #only #@elinagittHuB the download #link with #total assess to coin and other digital properties and other NFT's  

Psst, this issue will be closed with a templated response if it isn't a documentation update request.

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
