### ISSUE TITLE
Docs update request: /deployment-addresses 0x64C79a30cDeA78A6DCF4b0899455674d6849010b

### ISSUE THREAD

**Issue by MarekSyk** [ArbitrumFoundation/docs#353]
Source: https://docs.arbitrum.foundation/deployment-addresses 0x64C79a30cDeA78A6DCF4b0899455674d6849010b

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.

**Comment by symbolpunk** [comment]
Hi there! It looks like you submitted an update request template without filling in the details. I'm going to close this for now, but feel free to reopen if you have a specific update request.💙🧡
