### ISSUE TITLE
Docs update request: /airdrop-eligibility-distribution

### ISSUE THREAD

**Issue by harjinders54** [ArbitrumFoundation/docs#354]
Source: https://docs.arbitrum.foundation/airdrop-eligibility-distribution i am all task done arbitrum but i am not eligible for token i do not why i am not eligible i already submit request 20th march support team it is request no 1013556 also submit pdf file 
[photo_2023-03-20 13.58.31.pdf](https://github.com/ArbitrumFoundation/docs/files/11132892/photo_2023-03-20.13.58.31.pdf)
please check pdf file i do not what is issue please inform me

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
