### ISSUE TITLE
Docs update request: /gentle-intro-dao-governance

### ISSUE THREAD

**Issue by adipradikda** [ArbitrumFoundation/docs#357]
Source: https://docs.arbitrum.foundation/gentle-intro-dao-governance

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.

can i sill got the ARB token pls

**Comment by symbolpunk** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't directly related to docs. These non-docs issues are reviewed periodically, so they are useful. But you probably won't receive a response to non-docs issues here in the docs repo.

Check out the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you 🧡💙
