### ISSUE TITLE
Docs update request: /how-tos/carboidratos

### ISSUE THREAD

**Issue by Alocrs** [ArbitrumFoundation/docs#427]
Source: https://docs.arbitrum.foundation/how-tos/create-submit-dao-proposal

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.

**Comment by Alocrs** [comment]
Entrei para receber arbitrum..aqui neste site não consta nada de cripto..porém na página inicial consta minha mineração que vai vencer em setembro..o que preciso fazer ?

**Comment by DZGoldman** [comment]
Conecte su billetera en el sitio https://arbitrum.foundation/; si es elegible para tokens, puede reclamarlos allí (traducido con google translate :))
