### ISSUE TITLE
How can we input our own data to this program.  and public keys?

### ISSUE THREAD

**Issue by Qmig** [ArbitrumFoundation/docs#491]
- [ ] How can we input our own data to this program. I.e : RSZ sigs @and public keys?

There's so many programs thats coded but use generators.. Which are pointless. 

_Originally posted by @RoyNahar in https://github.com/bytemare/ecdsa-keyrec/issues/4_

**Comment by DZGoldman** [comment]
closing as it doesn't appear relevant to these docs; if there's a more specific question, feel free to reopen
