### ISSUE TITLE
incorporate aip 1.2 changes

### ISSUE THREAD

**Issue by fredlacs** [ArbitrumFoundation/docs#560]
AIP 1.2 has passed onchain, but the docs don't yet reflect the updates
https://www.tally.xyz/gov/arbitrum/proposal/77049969659962393408182308518930939247285848107346513112985531885924337078488

**Comment by DZGoldman** [comment]
should the docs reflect the changes after it passes, or after it executes? I think executes

**Comment by DZGoldman** [comment]
constitution updated https://github.com/ArbitrumFoundation/docs/pull/385
