### ISSUE TITLE
Arb/aa

### ISSUE THREAD

**Issue by Captainaa40** [ArbitrumFoundation/docs#605]

**Comment by Captainaa40** [comment]
Waoooo

**Comment by anhlam2234** [comment]
What

**Comment by HAAH10** [comment]
??????

**Comment by Captainaa40** [comment]
view it on GitHub<https://github.com/ArbitrumFoundation/docs/issues/605#event-10146019014>
دریافت از Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
