### ISSUE TITLE
Docs update request: /dao-constitution

### ISSUE THREAD

**Issue by B-oxygen** [ArbitrumFoundation/docs#629]
Source: https://docs.arbitrum.foundation/dao-constitution

Request: (how can we help?)

https://github.com/ArbitrumFoundation/docs/blob/main/docs/concepts/dao-vote.md 
The link above is based on 5,000,000, but the Constitution is based on 1,000,000, so I'm confused as to what the criteria is.

Psst, this issue will be closed with a templated response if it isn't a documentation update request.

**Comment by DZGoldman** [comment]
yep, the docs were out of date (the threshold was updated in AIP1.2), fixed [here](https://github.com/ArbitrumFoundation/docs/pull/630), good catch, ty!
