### ISSUE TITLE
Como reivindico essa cripitomoedas que e minha como prova minha propriedade

### ISSUE THREAD

**Issue by Zanatta2012** [ArbitrumFoundation/docs#713]
Source: https://docs.arbitrum.foundation/deployment-addresses

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.

**Comment by DZGoldman** [comment]
https://docs.arbitrum.foundation/dao-faqs#is-the-arb-airdrop-still-live
