### ISSUE TITLE
0x8a6edaf0a51ff37ee58f5236e2001ff787aefd0a

### ISSUE THREAD

**Issue by Kazy0004** [ArbitrumFoundation/docs#825]
Hello, I would like to know if I have any contribution with you

**Comment by kickym0802** [comment]
yahya saleh ***@***.***>於 2024年6月1日 週六，上午4:05寫道：

**Comment by kickym0802** [comment]
yahya saleh ***@***.***>於 2024年12月3日 週二，下午10:47寫道：
